FROM node:22-slim AS base
# turn off the nuisance nodejs update message
ARG NO_UPDATE_NOTIFIER=true
ENV NO_UPDATE_NOTIFIER=true
RUN npm config set update-notifier false
# Install dependencies for node-gyp and ffmpeg
RUN apt update && apt install -y ffmpeg python3 make g++ && rm -rf /var/lib/apt/lists/*

# create app directory
FROM base AS testbuild
WORKDIR /app
ENV NODE_ENV=test
ENV TF_CPP_MIN_LOG_LEVEL=2
ENV TF_ENABLE_ONEDNN_OPTS: '1'
COPY ./package*.json ./
COPY ./tsconfig.json ./tsconfig.json
RUN npm ci

FROM testbuild AS test-service
COPY ./src ./src
COPY ./tests ./tests
COPY ./shepherd.config.test.json shepherd.config.json
