FROM node:18-slim as base

# turn off the nuisance nodejs update message 
ARG NO_UPDATE_NOTIFIER=true
ENV NO_UPDATE_NOTIFIER=true
RUN npm config set update-notifier false
# create app directory
WORKDIR /app

FROM base as test
COPY tsconfig.json tsconfig.json
COPY package*.json ./
RUN npm ci
COPY . .
# COPY shepherd.config.test.json shepherd.config.json
