FROM node:14 as base

# turn off the nuisance update message 
ARG NO_UPDATE_NOTIFIER=true
ENV NO_UPDATE_NOTIFIER=true
RUN npm config set update-notifier false

# install ffmpeg dependency
RUN apt update && apt install ffmpeg -y

# create app directory
WORKDIR /app

FROM base as test
COPY package*.json ./
RUN npm ci
COPY . .
COPY shepherd.config.test.json shepherd.config.json
RUN npm install -g knex ts-node
