#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running post-merge hook"

git diff --name-only HEAD@{1} HEAD | grep -e 'package-lock.json$' | while read -r lockfile; do
  if [ -f "$lockfile" ]; then
    dir=$(dirname "$lockfile")
    echo "$lockfile change detected. Running 'npm ci' in '$dir'..."
    (cd "$dir" && npm ci)
  else
    echo "$lockfile was deleted. Skipping 'npm ci'."
  fi
done
